# These interface functions were automatically generated by
# mygpt::update_mygpt()
#
# Do not change the code below

mygpt_code = function() gpt4r::run_tpl_addin("code", "mygpt")
mygpt_quiz = function() gpt4r::run_tpl_addin("quiz", "mygpt")
mygpt_rewrite = function() gpt4r::run_tpl_addin("rewrite", "mygpt")
mygpt_suggest = function() gpt4r::run_tpl_addin("suggest", "mygpt")
