addin_update_mygpt = function(...) {
  library(mygpt)
  update_mygpt()
}

update_mygpt = function(project.dir = find_mygpt_dir()) {
  if (!check_mygpt_dir(project.dir)) {
    cat("\nNo upate took place as no correct dir to mygpt was found or provided.")
    return(invisible())
  }
  dir = project.dir

  tpl.dir = file.path(project.dir, "inst/templates")
  tpl.files = list.files(tpl.dir, glob2rx("*.y*ml"),full.names = TRUE)
  tpl.ids = tools::file_path_sans_ext(basename(tpl.files))

  cat(paste0("\nParse templates...\n"))


  tpl.li = lapply(tpl.files, function(file) {
    tpl = yaml::read_yaml(file)
    tpl$id = tools::file_path_sans_ext(basename(file))
    tpl
  })
  names(tpl.li) = tpl.ids
  tpl.li

  cat(paste0("\nPrepare package code for templates: ", paste0(tpl.ids, collapse=", "), "\n"))

  # Create code for inst/rstudio/addins.dcf

  addins.dcf = sapply(tpl.li, function(tpl) {
    if (is.null(tpl$description)) {
      tpl$description = tpl$label
    }
    glue_text(
"Name: {{label}}
Description: {{description}}
Binding: mygpt_{{id}}
Interactive: false
", tpl
    )
  })

  addins.dcf = c(
    addins.dcf,
'Name: Update mygpt
Description: Run this addin if you have removed or added new templates
Binding: addin_update_mygpt
Interactive: false
'
  )
  dcf.file = file.path(project.dir, "inst/rstudio/addins.dcf")
  writeLines(addins.dcf, dcf.file)

  addin.links = paste0(
    'mygpt_', tpl.ids, ' = function() gpt4r::run_tpl_addin("', tpl.ids,'", "mygpt")',
    collapse = "\n"
  )
  addin.links = paste0(
'# These interface functions were automatically generated by
# mygpt::update_mygpt()
#
# Do not change the code below

',
    addin.links
  )
  addin.links.file = file.path(project.dir, "R/addin_links.R")
  writeLines(addin.links, addin.links.file)


  cat("\nBuild and install mygpt package...\n")
  devtools::install(project.dir)
  return(invisible())
}




find_mygpt_dir = function() {
  dir = rstudioapi::getActiveProject()
  if (check_mygpt_dir(dir)) return(dir)
  dir = getOption(".last.mygpt.dir")
  if (check_mygpt_dir(dir)) return(dir)

  dir = getwd()
  if (check_mygpt_dir(dir)) return(dir)

  cat("\nCould not find directory of mygpt project. Please open the project in RStudio if you want to update it.")
  return(NA)
}

check_mygpt_dir = function(dir, set.as.last.dir = TRUE) {
  if (isTRUE(dir=="") | is.na(dir)) return(FALSE)
  if (!file.exists(file.path(dir,"mygpt.Rproj"))) {
    return(FALSE)
  }

  if (set.as.last.dir) {
    options(.last.mygpt.dir = dir)
  }
  return(TRUE)
}
